<!DOCTYPE html>
<html lang="en">

<head>
    <?php $this->load->view('admin-dashboard/fragments/head-code'); ?>
</head>

<body class="animsition">
    <div class="page-wrapper">

        <?php $this->load->view('admin-dashboard/fragments/mobile-header'); ?>
        <?php $this->load->view('admin-dashboard/fragments/menu-side-bar'); ?>

        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <?php $this->load->view('admin-dashboard/fragments/header'); ?>
            <!-- HEADER DESKTOP-->

            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <!-- DATA TABLE -->
                                <h3 class="title-5 m-b-35">Admin Authentication Pin</h3>
                                <div class="table-data__tool">

                                    <div class="table-data__tool-right">
                                        <a href="<?= base_url('admin/pin/generate') ?>" class="au-btn au-btn-icon au-btn--green au-btn--small">
                                            <i class="zmdi zmdi-key"></i>Generate New Pin
                                        </a>
                                    </div>
                                </div>
                                <?php if ($this->session->has_userdata('pinError')) : ?>
                                    <div class="alert alert-danger text-center">
                                        <?php echo $this->session->pinError;
                                        $this->session->unset_userdata('pinError');
                                        ?>
                                    </div>
                                <?php endif; ?>
                                <?php if ($this->session->has_userdata('pinMsg')) : ?>
                                    <div class="alert alert-success text-center">
                                        <?php echo $this->session->pinMsg;
                                        $this->session->unset_userdata('pinMsg');
                                        ?>
                                    </div>
                                <?php endif; ?>
                                <div class="table-responsive table--no-card m-b-30">
                                    <table id="pinsTable" class="table table-borderless table-striped table-earning">
                                        <thead>
                                            <tr>
                                                <th>Pin</th>
                                                <th>Generated By</th>
                                                <th>Used By</th>
                                                <th>Date Generated</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            <?php
                                            if (count((array) $pins) > 0) :
                                                foreach ($pins as $pin) : ?>
                                                    <tr class="tr-shadow">
                                                        <td><?= $pin->pin ?></td>
                                                        <td><?= $pin->created_by ?></td>
                                                        <td><?= $pin->used_by ?></td>
                                                        <td><?= $pin->date_created ?></td>
                                                        <td>
                                                            <?php if ($pin->no_of_usage > 0) : ?>
                                                                <span class="badge badge-danger">USED</span>
                                                            <?php else : ?>
                                                                <span class="badge badge-success">AVAILABLE</span>
                                                            <?php endif ?>
                                                        </td>
                                                    </tr>
                                                    <tr class="spacer"></tr>
                                            <?php endforeach;
                                            endif;
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                                <!-- END DATA TABLE -->
                            </div>
                        </div>
                        <?php $this->load->view('admin-dashboard/fragments/footer'); ?>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>

    </div>


    <?php $this->load->view('admin-dashboard/fragments/script'); ?>
    <script>
        $(document).ready(function() {
            $('li#pinPage').addClass("active");
        });
    </script>
</body>

</html>
<!-- end document-->